[package]
name = "adventofcode2025"
version = "0.1.0"
authors = ["Markus Fruhmann"]
edition = "2024"

[[bench]]
name = "adventofcode2025"
harness = false

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"

[dev-dependencies]
criterion = "0.8.0"
